### ISSUE TITLE
TypeError: object Lock can't be used in 'await' expression

### ISSUE THREAD

**Issue by egabrum** [rambo/python-scpi#11]
```
    with (await self.lock):
TypeError: object Lock can't be used in 'await' expression
```

I get this with python 3.9 while trying to use the TCPTransport
Is there any type of incompatibility with py 3.9 ?

Edit: Relevant:
https://stackoverflow.com/questions/65111601/what-is-the-difference-between-async-with-lock-and-with-await-lock
"The second form with await lock is deprecated since Python 3.7 and is removed in Python 3.9."

**Comment by rambo** [comment]
I wonder if `async with self.lock` just works on older python versions as well. I was very new to asyncio back then I made this so there's a bunch of other not-great stuff there too, the next time I need to actually do something with SCPI I will probably end up doing some heavy duty refactoring/rewriting.

**Comment by rambo** [comment]
Also it seems TCPTransport wasn't even done by me :)

**Comment by egabrum** [comment]
> 
> 
> Also it seems TCPTransport wasn't even done by me :)

Right. I needed to use TCPTransport , but it's not in the Pypi package. So please, push it to Pypi if you get around fixing it :-)

**Comment by egabrum** [comment]
> 
> 
> I wonder if `async with self.lock` just works on older python versions as well. I was very new to asyncio back then I made this so there's a bunch of other not-great stuff there too, the next time I need to actually do something with SCPI I will probably end up doing some heavy duty refactoring/rewriting.

I've done a quick, non-exhaustive check and `async with self.lock` seems to work on python 3.7.9
(I only changed it in SCPIProtocol.ask())
