### ISSUE TITLE
scpi 2.4.0 available in pypi

### ISSUE THREAD

**Issue by Lorac** [rambo/python-scpi#19]
But there is no tag or changelog?

**Comment by rambo** [comment]
tag made, I have been too lazy to maintain a changelog so the commit history is what people get on that front.

**Comment by Lorac** [comment]
@rambo Thanks for the tag, 

FYI: tools like https://github.com/renovatebot/renovate fetches a changelog from Github and display it inside a pull request. It makes it easier to see if there is a breaking change from the library straight from the pr description.
