### ISSUE TITLE
python 3 and pip install fails

### ISSUE THREAD

**Issue by gicking** [rambo/python-scpi#2]
hi Eero,

hope you still maintain this repo...!?

I have a problem installing "scpi" via pip. Specifically I get the following error message: 

georg@BueroPC:~$ sudo -H pip install scpi 
Collecting scpi
  Downloading scpi-0.6.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-tks6vbwf/scpi/setup.py", line 7
        except subprocess.CalledProcessError,e:
                                            ^
    SyntaxError: invalid syntax    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-tks6vbwf/scpi/

Clearing cache and using pip3 don't solve the issue. Any idea what goes wrong here?  I'm using Ubuntu 16.04. For your help - and your repo - thanks a lot!

Greetings from Germany,
Georg Icking-Konert

**Comment by gicking** [comment]
found it, the problem is that python 3.x:

- exceptions no longer supports comma, see [here](https://stackoverflow.com/questions/2535760/python-try-except-comma-vs-as-in-except)
- require print with brackets, see [here]()

You can download a python 3.x compatible fix (with only the above changes) from [here](https://www.dropbox.com/s/tj7bvfgc842ns0p/scpi-0.6.5.zip?dl=0). Unfortunately I am not too familiar with Github and how to make changes. Sorry for the inconvenience!

**Comment by gicking** [comment]
darn, now I struggle with the example! The problem is obviously caused again by differences between Python 2.x and 3.c...   :-(

Python 2.7.12 is ok:
georg@BueroPC: python -i ./hp6632b.py /dev/ttyUSB0
 *** getRI changed to 0 *** 
 *** getCD changed to 0 *** 
 *** getDSR changed to 0 *** 
 *** getCTS changed to 0 *** 


Python 3.5.2 fails: 
georg@BueroPC: python3 -i ./hp6632b.py /dev/ttyUSB0
Traceback (most recent call last):
  File "./hp6632b.py", line 17, in <module>
    dev = hp6632b.rs232(sys.argv[1], rtscts=True)
  File "/usr/local/lib/python3.5/dist-packages/scpi/devices/hp6632b.py", line 103, in rs232
    from scpi.transports import rs232 as serial_transport
  File "/usr/local/lib/python3.5/dist-packages/scpi/transports/__init__.py", line 3, in <module>
    from .rs232 import transports_rs232 as rs232
  File "/usr/local/lib/python3.5/dist-packages/scpi/transports/rs232.py", line 9, in <module>
    from baseclass import transports_base
ImportError: No module named 'baseclass'
>>>

**Comment by rambo** [comment]
Yeah it was originally made for python 2.7, not sure when I'm going to have time to do python3 support so that I've actually tested it to work. `2to3` probably will not catch the import path problem.

**Comment by gicking** [comment]
ok, now I got it to "work" also under python3 - at least the above error is gone.
Fix was simple: in "transports/rs232.py" line 9 replace 
"from .baseclass import transports_base"  with
"from baseclass import transports_base"  (note the dot)

HOWEVER, both under python2 and python3 aIl I get is below output from transports_rs232.serial_reader():

georg@BueroPC: python -i hp6632b.py /dev/ttyUSB0 
 *** getRI changed to 0 *** 
 *** getCD changed to 0 *** 
 *** getDSR changed to 0 *** 
 *** getCTS changed to 0 *** 

To cut things short: if I want to send "*IDN?" and print the reponse, how do I do that? Any help is highly appreciated! 

PS: you find the latest version [here](https://www.dropbox.com/s/u0e6iybq0hwud56/scpi-0.6.5.zip?dl=0)
