### ISSUE TITLE
Can't get a response from my generator

### ISSUE THREAD

**Issue by Lorac** [rambo/python-scpi#5]
I have this class I can use it to set voltage, set frequencies, but it can't read the responses. I did upgrade from the non-async version to this async version since then I can't get the responses back.

```
class AG33250A(PowerSupply, MultiMeter):
    """Adds the Agilent 33250A specific SCPI commands as methods"""

    def __init__(self, transport, loop):
        """Initializes a device for the given transport"""
        super().__init__(transport, use_safe_variants=False)
        self._voltage = 0.1
        self._frequency = 1000.0
        self.max_voltage = 10
        self.loop = loop

    def identify(self):
        """
        Return the identification of the generator

        :returns: a list of string:  Agilent Technologies,33250A,0,m.mm-l.ll-f.ff-gg-p
        m.mm = Main firmware revision number
        l.ll = Loader firmware revision number
        f.ff = I/O processor firmware revision number
        gg = Gate array revision number
        p = Printed circuit board revision number
        """
        return self.loop.run_until_complete(super().identify())
.....
```

Since `run_until_complete` never finishes. It can't find a response then it hits the maximum recursion depth exceeded.

```
    return self.gen.send(None)
  File "/home/roussinm/.local/lib/python3.5/site-packages/scpi/scpi.py", line 196, in ask
    await self.check_error(command)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
  File "/home/roussinm/.local/lib/python3.5/site-packages/scpi/scpi.py", line 162, in check_error
    code, errstr = await self.get_error()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
  File "/home/roussinm/.local/lib/python3.5/site-packages/scpi/scpi.py", line 151, in get_error
    response = await self.ask('SYST:ERR?')
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
... 
```

**Comment by rambo** [comment]
Overriding an async method with non async one sounds like a bad idea in general. Use the https://github.com/rambo/python-scpi/blob/master/scpi/wrapper.py wrapper if you want your code to block while waiting for responses.

Here the original command timeouts and then something goes wrong when trying to determine a more specific error code https://github.com/rambo/python-scpi/blob/master/scpi/scpi.py#L196

Also the https://pyserial.readthedocs.io/en/latest/url_handlers.html#spy serial url prefix is your friend when debugging what's going on.

**Comment by Lorac** [comment]
Looks like everything is fine on the generator side, I can see the `identify` returns the data, but it doesn't trigger the `message_received` in https://github.com/rambo/python-scpi/blob/master/scpi/transports/baseclass.py#L36

**Comment by rambo** [comment]
Can you post your full code  and output from spy:// ? Right now (apart from that race condition possibility listed there) the easy checks are baudrate and line endings (if the device only send LF and the linereader expects CRLF for example)

**Comment by Lorac** [comment]
```

**Comment by Lorac** [comment]
So I was able to hack the TERMINATOR with

```
class AG33250ATransport(RS232Transport):
    def __init__(self, serial_device):
        super().__init__(serial_device)
        self.serialhandler.protocol.TERMINATOR = b'\n'
```

and now it works.

**Comment by rambo** [comment]
Yeah, been busy but indeed the spy shows the line terminator is not what the transport expects but this looks like workable solution.
