### ISSUE TITLE
Will this work with /dev/usbtmc5?

### ISSUE THREAD

**Issue by fgervais** [rambo/python-scpi#8]
Hi,

I'm new to this and I don't want to break my brand new things :)

When I plug my IT6922A power supply I get a `/dev/usbtmc5`. I would have expected something more like `/dev/ttyUSB0` or something.

Do you know if I can just use `/dev/usbtmc5` with this lib as if it would be `/dev/ttyUSB0`?

**Comment by rambo** [comment]
if it acts like a standard serial port it should work.
